#ifndef DIALOG_H
#define DIALOG_H

#include "city.h"
#include <QDialog>

namespace Ui {  // qt desginer created UI class already so we put class dialog inside this namespace
class Dialog;
}

class Dialog : public QDialog
{
    Q_OBJECT // necessary in all QObject-derived classes

public:
    explicit Dialog(QWidget *parent = nullptr);
    ~Dialog();

    bool stadtErstellen();
    City* getStadt();

private:
    Ui::Dialog *ui; // This is a pointer to the Ui::Dialog object that is automatically generated by Qt.
    City* stadt;
};
#endif // DIALOG_H
