#ifndef DIALOGSTREET_H
#define DIALOGSTREET_H

#include <QDialog>

namespace Ui {      // qt desginer created UI class already so we put class dialog inside this namespace
class DialogStreet;
}

class DialogStreet : public QDialog
{
    Q_OBJECT        // necessary in all QObject-derived classes

public:
    explicit DialogStreet(QWidget *parent = nullptr);
    ~DialogStreet();

    void strasseErstellen();
    QString getStrasseStadt1();
    QString getStrasseStadt2();

private:
    Ui::DialogStreet *ui; // This is a pointer to the Ui::DialogStreet object that is automatically generated by Qt.
    QString strasseStadt1;
    QString strasseStadt2;
};

#endif // DIALOGSTREET_H
