#ifndef ROUTE_H
#define ROUTE_H

#include <QDialog>

namespace Ui {  // qt desginer created UI class already so we put class dialog inside this namespace
class Route;
}

class Route : public QDialog
{
    Q_OBJECT // necessary in all QObject-derived classes

public:
    explicit Route(QWidget *parent = nullptr);
    ~Route();

    QString getStart();
    QString getZiel();

    void setStart();
    void setZiel();

private:
    Ui::Route *ui; // This is a pointer to the Ui::Route object that is automatically generated by Qt.
    QString start;
    QString ziel;
};

#endif // ROUTE_H
